### ISSUE TITLE
master branch is broken

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#146]
The current master branch is broken because there are some issues with the current Barclay version and the GATK one. This is caused whenever a tool is run, throwing the following exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.broadinstitute.barclay.argparser.CommandLineParser.usage(Z)Ljava/lang/String;
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.getUsage(CommandLineProgram.java:269)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:146)
        at org.magicdgs.readtools.Main.main(Main.java:74)
```

We should add a test for this in Travis to avoid regression, because I don't know when I broke it.

**Comment by magicDGS** [comment]
This is solved now with #147. But we need a way to check if the tools are broken or not...

**Comment by magicDGS** [comment]
There is a try in #149 for that, but we require to run an actual tool for this...

**Comment by magicDGS** [comment]
There is a try for the test in https://github.com/magicDGS/ReadTools/pull/150, so closing the issue.
