### ISSUE TITLE
Catch "Premature end of file" error to throw an user exception for corrupted files

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#359]
@robmaz reported an UNEXPECTED ERROR while running `TrimReads` with a supposedly corrupted BAM file, which looks that it's comming from the `BlockCompressedInputStream` in HTSJDK:

```
UNEXPECTED ERROR: Premature end of file: /home/vetlinux02/Rupert/prj/Wolbachia/09PoolSeqData/HOT___r05_F180__72.bam
```

The output file is not generated, and the input comes from a ReadTools + Picard (v. 2.12.1-SNAPSHOT) pipeline: 1) StandardizeReads, 2) AssignReadGroupsByBarcode, 3) Picard AddOrReplaceReadGroups and 4) TrimReads

Until we know if the corrupted files are comming from one of the previous steps from the pipeline (which looks unlikely as far as we explore the issue), we can catch the exception (which is a `SAMException`) and rethrow as an `UserException` to show the user that it is corrupted. We should see the exact stack-trace where the problem happen, because maybe it should be catched in the GATK-side.

I will try to get a small corrupted file to test this case.

**Comment by magicDGS** [comment]
Stack trace for small corrupted file (should be added to test this):

```
Runtime.totalMemory()=257425408
***********************************************************************

UNEXPECTED ERROR: Premature end of file: /Users/daniel/workspaces/ReadTools/tmp/COLD__r10_F051_CORRUPT.bam

***********************************************************************
Please, search for this error in our issue tracker or post a new one:
	https://github.com/magicDGS/ReadTools/issues
htsjdk.samtools.FileTruncatedException: Premature end of file: /Users/daniel/workspaces/ReadTools/tmp/COLD__r10_F051_CORRUPT.bam
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:530)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:418)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
	at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:209)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:829)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:803)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
	at htsjdk.samtools.util.QualityEncodingDetector.add(QualityEncodingDetector.java:174)
	at htsjdk.samtools.util.QualityEncodingDetector.detect(QualityEncodingDetector.java:333)
	at htsjdk.samtools.util.QualityEncodingDetector.detect(QualityEncodingDetector.java:340)
	at htsjdk.samtools.util.QualityEncodingDetector.detect(QualityEncodingDetector.java:344)
	at org.magicdgs.readtools.engine.sourcehandler.SamSourceHandler.getReaderQualityEncoding(SamSourceHandler.java:92)
	at org.magicdgs.readtools.engine.sourcehandler.SamSourceHandler.getReaderQualityEncoding(SamSourceHandler.java:48)
	at org.magicdgs.readtools.engine.sourcehandler.FileSourceHandler.lambda$getQualityEncoding$64(FileSourceHandler.java:94)
	at org.magicdgs.readtools.engine.sourcehandler.FileSourceHandler.readAndClose(FileSourceHandler.java:110)
	at org.magicdgs.readtools.engine.sourcehandler.FileSourceHandler.getQualityEncoding(FileSourceHandler.java:94)
	at org.magicdgs.readtools.engine.sourcehandler.SamSourceHandler.getQualityEncoding(SamSourceHandler.java:48)
	at org.magicdgs.readtools.engine.RTDataSource.originalEncoding(RTDataSource.java:227)
	at org.magicdgs.readtools.engine.RTDataSource.getOriginalQualityEncoding(RTDataSource.java:179)
	at org.magicdgs.readtools.engine.ReadToolsWalker.onStartup(ReadToolsWalker.java:90)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:117)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.magicdgs.readtools.Main.main(Main.java:84
```
